apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/codefresh-io/argocd-base/argo-cd?ref=v0.1.6

patchesStrategicMerge:
  - application-controller.yaml
  - server.yaml
