apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{.EnvName}}"
  namespace: "{{.EnvName}}-argocd"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/managed-by: argo-installer
    app.kubernetes.io/name: root
spec:
  project: "{{.EnvName}}"
  source:
    repoURL: {{.RepoURL}}
    targetRevision: HEAD
    path: argocd-apps/{{.EnvName}}
  destination:
    server: https://kubernetes.default.svc
    namespace: "{{.EnvName}}-argocd"
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /status
