apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{.EnvName}}"
  namespace: "{{.EnvName}}-argocd"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    ent-managed-by: codefresh.io
    cf-name: root
spec:
  project: "{{.EnvName}}"
  source:
    repoURL: https://github.com/{{.RepoOwner}}/{{.RepoName}}
    targetRevision: HEAD
    path: argocd-apps/{{.EnvName}}
  destination:
    server: https://kubernetes.default.svc
    namespace: "{{.EnvName}}-argocd"
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - kind: Application
      jsonPointers:
        - /status
