apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: "{{.EnvName}}"
  namespace: "{{.EnvName}}-argocd"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/managed-by: argo-installer
    app.kubernetes.io/name: project
spec:
  description: "{{.EnvName}} project"
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
