apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - sealed-secret.json

namespace: "{{.EnvName}}-argocd"

configMapGenerator:
  - name: argocd-cm
    behavior: merge
    files:
      - repository.credentials

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd

patches:
  - path: patches/clusterRoleBinding.json
    target:
      kind: ClusterRoleBinding
      name: argocd-application-controller
  - path: patches/clusterRoleBinding.json
    target:
      kind: ClusterRoleBinding
      name: argocd-server
#  - path: patches/clusterRole_argocd-application-controller.json
#    target:
#      kind: ClusterRole
#      name: argocd-application-controller
#   - path: patches/clusterRole_argocd-server.json
#     target:
#       kind: ClusterRole
#       name: argocd-server
#   - path: patches/clusterRoleBinding_argocd-application-controller.json
#     target:
#       kind: ClusterRoleBinding
#       name: argocd-application-controller
#   - path: patches/clusterRoleBinding_argocd-server.json
#     target:
#       kind: ClusterRoleBinding
#       name: argocd-server
