apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - cluster-rbac
  - sealed-secret.json

namespace: "{{.EnvName}}-argocd"

configMapGenerator:
  - name: argocd-cm
    behavior: merge
    files:
      - repository.credentials

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd

patches:
- path: clusterRoleBinding_patch.json
  target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRoleBinding
    name: argocd-application-controller
- path: clusterRoleBinding_patch.json
  target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRoleBinding
    name: argocd-server
