apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{.EnvName}}-argo-workflows"
  namespace: "{{.EnvName}}-argocd"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    ent-managed-by: codefresh.io
    cf-name: argo-workflows
spec:
  project: {{.EnvName}}
  source:
    repoURL: https://github.com/{{.RepoOwner}}/{{.RepoName}}
    targetRevision: HEAD
    path: kustomize/components/argo-workflows/overlays/{{.EnvName}}
  destination:
    server: https://kubernetes.default.svc
    namespace: "{{.EnvName}}-argo-workflows"
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
