apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{.EnvName}}-argo-cd"
  namespace: "{{.EnvName}}-argocd"
  labels:
    app.kubernetes.io/managed-by: argo-installer
    app.kubernetes.io/name: argo-cd
spec:
  project: {{.EnvName}}
  source:
    repoURL: {{.RepoURL}}
    targetRevision: HEAD
    path: kustomize/components/argo-cd/overlays/{{.EnvName}}
  destination:
    server: https://kubernetes.default.svc
    namespace: "{{.EnvName}}-argocd"
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /status
