apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{.EnvName}}-sealed-secrets"
  namespace: "{{.EnvName}}-argocd"
  labels:
    ent-managed-by: codefresh.io
    cf-name: sealed-secrets
spec:
  project: {{.EnvName}}
  source:
    repoURL: {{.RepoUrl}}
    targetRevision: HEAD
    path: kustomize/components/sealed-secrets/overlays/{{.EnvName}}
  destination:
    server: https://kubernetes.default.svc
    namespace: "{{.EnvName}}-argocd"
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /status
