apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{.EnvName}}-components"
  namespace: "{{.EnvName}}-argocd"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    ent-managed-by: codefresh.io
    cf-name: components
spec:
  project: "{{.EnvName}}"
  source:
    repoURL: {{.RepoURL}}
    targetRevision: HEAD
    path: argocd-apps/{{.EnvName}}/components
  destination:
    server: https://kubernetes.default.svc
    namespace: "{{.EnvName}}-argocd"
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /status
