apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{.EnvName}}-entities"
  namespace: "{{.EnvName}}-argocd"
  labels:
    ent-managed-by: codefresh.io
    cf-name: entities
spec:
  project: "{{.EnvName}}"
  source:
    repoURL: https://github.com/{{.RepoOwner}}/{{.RepoName}}
    targetRevision: HEAD
    path: kustomize/entities/overlays/{{.EnvName}}
  destination:
    server: https://kubernetes.default.svc
    namespace: "{{.EnvName}}-entities"
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /status
